// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    MINDCLIP_DATA: D1Database;
    
    SECRET_KEY: string;
    USERNAME: string;
    PASSWORD: string;
}
